<?php
/*
 * This file is part of the F0ska/AutoGrid package.
 *
 * (c) Victor Shvets
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace F0ska\AutoGridBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('f0ska_auto_grid');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->arrayNode('template')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('theme')->defaultValue('@F0skaAutoGrid/bootstrap_5')->end()
                        ->scalarNode('base')->defaultValue('base.html.twig')->end()
                        ->scalarNode('icons')->defaultValue('@F0skaAutoGrid/_icons.html.twig')->end()
                        ->arrayNode('form_themes')
                            ->prototype('scalar')->end()
                            ->defaultValue(['bootstrap_5_layout.html.twig'])
                        ->end()
                        ->arrayNode('action')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('grid')->defaultValue('action/grid.html.twig')->end()
                                ->scalarNode('form')->defaultValue('action/form.html.twig')->end()
                                ->scalarNode('view')->defaultValue('action/view.html.twig')->end()
                                ->scalarNode('error')->defaultValue('action/error.html.twig')->end()
                            ->end()
                        ->end()
                        ->arrayNode('field')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('debug')->defaultValue('field/debug.html.twig')->end()
                                ->scalarNode('text')->defaultValue('field/text.html.twig')->end()
                                ->scalarNode('date')->defaultValue('field/date.html.twig')->end()
                                ->scalarNode('choice')->defaultValue('field/choice.html.twig')->end()
                                ->scalarNode('boolean')->defaultValue('field/boolean.html.twig')->end()
                                ->scalarNode('simple_array')->defaultValue('field/array.html.twig')->end()
                                ->scalarNode('json')->defaultValue('field/json.html.twig')->end()
                                ->scalarNode('ascii_string')->defaultValue('field/ascii.html.twig')->end()
                                ->scalarNode('binary')->defaultValue('field/binary.html.twig')->end()
                            ->end()
                        ->end()
                        ->arrayNode('fieldset')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('view')->defaultValue('fieldset/view.html.twig')->end()
                                ->scalarNode('form')->defaultValue('fieldset/form.html.twig')->end()
                            ->end()
                        ->end()
                        ->arrayNode('grid')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('advanced_filter')->defaultValue('grid/advanced_filter.html.twig')->end()
                                ->scalarNode('colgroup')->defaultValue('grid/colgroup.html.twig')->end()
                                ->scalarNode('column_header')->defaultValue('grid/column_header.html.twig')->end()
                                ->scalarNode('column_header_action')->defaultValue('grid/column_header_action.html.twig')->end()
                                ->scalarNode('column_header_filter')->defaultValue('grid/column_header_filter.html.twig')->end()
                                ->scalarNode('column_header_massaction')->defaultValue('grid/column_header_massaction.html.twig')->end()
                                ->scalarNode('column_header_sort')->defaultValue('grid/column_header_sort.html.twig')->end()
                                ->scalarNode('column_value')->defaultValue('grid/column_value.html.twig')->end()
                                ->scalarNode('column_value_action')->defaultValue('grid/column_value_action.html.twig')->end()
                                ->scalarNode('column_value_massaction')->defaultValue('grid/column_value_massaction.html.twig')->end()
                                ->scalarNode('grid_number_per_page')->defaultValue('grid/grid_number_per_page.html.twig')->end()
                                ->scalarNode('grid_pagination')->defaultValue('grid/grid_pagination.html.twig')->end()
                                ->scalarNode('row_class')->defaultValue('grid/row_class.html.twig')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('view')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('friendly_id')->defaultValue('autogrid')->end()
                        ->booleanNode('show_entity_title')->defaultTrue()->end()
                        ->arrayNode('field_formats')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('date')->defaultValue('Y-m-d')->end()
                                ->scalarNode('time')->defaultValue('H:i')->end()
                                ->scalarNode('datetime')->defaultValue('Y-m-d H:i')->end()
                                ->scalarNode('interval')->defaultValue('%Yy, %mm, %dd')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('grid')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('truncate_text')->defaultValue(55)->end()
                        ->arrayNode('pagination_limits')
                            ->prototype('integer')->end()
                            ->defaultValue([10, 50, 100])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('buttons')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('view')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('display_in_grid')->defaultTrue()->end()
                                ->booleanNode('display_in_edit')->defaultTrue()->end()
                            ->end()
                        ->end()
                        ->arrayNode('edit')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('display_in_grid')->defaultTrue()->end()
                                ->booleanNode('display_in_view')->defaultTrue()->end()
                            ->end()
                        ->end()
                        ->arrayNode('delete')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('display_in_grid')->defaultTrue()->end()
                                ->booleanNode('display_in_view')->defaultTrue()->end()
                                ->booleanNode('display_in_edit')->defaultTrue()->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('request')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('single_parameter_mode')->defaultFalse()->end()
                        ->scalarNode('single_parameter_code')->defaultValue('_ag')->end()
                        ->arrayNode('parameter_codes')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('id')->defaultValue('agId')->end()
                                ->scalarNode('action')->defaultValue('agAction')->end()
                                ->scalarNode('params')->defaultValue('agParams')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('session')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('store_navigation')->defaultTrue()->end()
                    ->end()
                ->end()
                ->arrayNode('form')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('default_boolean_as_select')->defaultFalse()->end()
                        ->booleanNode('default_date_filter_range')->defaultTrue()->end()
                        ->arrayNode('relation_label_candidates')
                            ->prototype('scalar')->end()
                            ->defaultValue(['title', 'label', 'name', 'code', 'subject', 'model', 'sku'])
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
