services:
    _defaults:
        public: false
        autowire: false
        autoconfigure: false

    F0ska\AutoGridBundle\:
        resource: '../src/{Builder/*,Service/*,Factory/*}'
        autowire: true

    F0ska\AutoGridBundle\Twig\:
        resource: '../src/Twig/*'
        lazy: true
        autowire: true
        autoconfigure: true

    F0ska\AutoGridBundle\Action\:
        resource: '../src/Action/*'
        tags: [ 'autogrid.action' ]
        autowire: true

    F0ska\AutoGridBundle\Condition\:
        resource: '../src/Condition/*'
        tags: [ 'autogrid.filter_condition' ]
        autowire: true

    F0ska\AutoGridBundle\ActionParameter\:
        resource: '../src/ActionParameter/*'
        tags: [ 'autogrid.action.parameter' ]
        autowire: true

    F0ska\AutoGridBundle\View\:
        resource: '../src/View/*'
        tags: [ 'autogrid.view_service' ]
        autowire: true

    F0ska\AutoGridBundle\Service\Provider\:
        resource: '../src/Service/Provider/*'
        autowire: true

    F0ska\AutoGridBundle\View\ViewServiceRegistry:
        autowire: true
        lazy: true
        arguments:
            $services: !tagged_iterator 'autogrid.view_service'

    F0ska\AutoGridBundle\Service\ConfigurationService:
        autowire: true
        arguments:
            $config: '%f0ska_auto_grid.config%'

    F0ska\AutoGridBundle\Service\ActionListService:
        autowire: true
        lazy: true
        arguments:
            $actions: !tagged_iterator 'autogrid.action'

    F0ska\AutoGridBundle\Service\ActionParametersListService:
        autowire: true
        lazy: true
        arguments:
            $actionParameters: !tagged_iterator 'autogrid.action.parameter'

    F0ska\AutoGridBundle\Service\PermissionService:
        autowire: true
        lazy: true

    F0ska\AutoGridBundle\Service\FilterConditionListService:
        autowire: true
        lazy: true
        arguments:
            $conditions: !tagged_iterator 'autogrid.filter_condition'

    F0ska\AutoGridBundle\Service\CustomizationService:
        autowire: true
        lazy: true
        arguments:
            $customizations: !tagged_iterator 'autogrid.customization'
